// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using SongEvents;
//
//    var song = Song.FromJson(jsonString);

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace SongEvents
{
    public partial class Song
    {
        [JsonProperty("rhythmEditor")]
        public RhythmEditor[] RhythmEditor { get; set; }
    }

    public partial class RhythmEditor
    {
        [JsonProperty("song")]
        public string Song { get; set; }

        [JsonProperty("events")]
        public Event[] Events { get; set; }
    }

    public partial class Event
    {
        [JsonProperty("timer")]
        public float Timer { get; set; }

        [JsonProperty("arrow")]
        public int Arrow { get; set; }
    }

    public partial class Song
    {
        public static Song FromJson(string json) => JsonConvert.DeserializeObject<Song>(json, SongEvents.Converter.Settings);

        public static Song LoadJson(string fileName)
        {
            string jsonString = File.ReadAllText(fileName);
            Song song = Song.FromJson(jsonString);

            return song;
        }

        public static void ExportJsonSong(Song song, string fileName)
        {
            File.WriteAllText(fileName, song.ToJson());
        }
    }

    public static class Serialize
    {
        public static string ToJson(this Song self) => JsonConvert.SerializeObject(self, SongEvents.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
